### ISSUE TITLE
Invalid Verification Link new email address

### ISSUE THREAD

**Issue by ELMEHDI2025** [rawilk/profile-filament-plugin#32]
### profile-filament-plugin Version

0.3.3

### Laravel Version

11.6

### Bug description

After clicking on the verification link. The process stops at the following error message:
![image](https://github.com/rawilk/profile-filament-plugin/assets/82848859/c5e79d98-003b-4e9e-a6f4-64c1a374e860)

### Steps to reproduce

Change the user's email, and open the Verify Email link.

**Comment by rawilk** [comment]
This will be resolved with a release today.
