### ISSUE TITLE
Not support multi-tenants..

### ISSUE THREAD

**Issue by ELMEHDI2025** [rawilk/profile-filament-plugin#53]
### profile-filament-plugin Version

0.4.1

### Laravel Version

11.25.0

### Bug description

After implementing multi-tenancy as stated in filamentphp.com and registering the profile-filament plugin in the panel. The email confirmation feature stops working with the following error message:
![Missing required parameter](https://github.com/user-attachments/assets/b1961253-2486-437f-9e2a-44331d0b1b23)

**Comment by ELMEHDI2025** [comment]
After trying again, the issue appeared specifically on the create tenant page (/new) directly after registering a new user. In addition to the email confirmation page (/email-verification/prompt).

**Comment by rawilk** [comment]
@ELMEHDI2025 Glad to see you figured it out. I haven't ran into any issues with multi-tenancy yet in my own projects with this plugin, however I also don't use multi-tenancy through Filament itself either.

**Comment by karpadiem** [comment]
For those searching for this later. this is how I fixed it:

The issue is that the route is registered with the tenant context. The user menu item is trying to render the url, but since there is not tenant set yet, that breaks and we get the error.

In my panel provider I disabled the user menu item by adding `->hideFromUserMenu()`
```
                ProfileFilamentPlugin::make()
                    ->swapComponent(
                        page:         ProfileInfoPage::class,
                        component:    ProfileInfo::class,
                        newComponent: CustomProfileInfo::class
                    )
                    ->hideFromUserMenu(),
```

Then, I recreated the menu item conditionally so that it only showed when there was a Tenant.

```
)->userMenuItems([
                'profile' => MenuItem::make()
                    ->visible(
                    //if filament tennant is not null
                        fn () => !is_null(Filament::getTenant()) && Filament::getTenant()->exists
                    )
                    ->label('Your Settings')
                    ->icon('carbon-settings')
                    ->url(
                        fn () => route('filament.attend.profile', ['tenant' => Filament::getTenant()->slug])
                    ),
            ])
```
